apiVersion: datumctl.datum.net/v1alpha1
kind: PluginList
items:
- apiVersion: datumctl.datum.net/v1alpha1
  kind: Plugin
  metadata:
    name: compute
  spec:
    shortDescription: Deploy and manage containerized workloads on Datum Cloud
    homepage: https://github.com/datum-cloud/compute
    version: v0.8.0-dev.7
    platforms:
    - selector:
        matchLabels:
          os: linux
          arch: amd64
      uri: https://github.com/datum-cloud/compute/releases/download/v0.8.0-dev.7/datumctl-compute_Linux_x86_64.tar.gz
      sha256: febd3a34a8191724571a3f2d0f0bbd4ed4230a6cba33be3df59005d419e383b3
    - selector:
        matchLabels:
          os: linux
          arch: arm64
      uri: https://github.com/datum-cloud/compute/releases/download/v0.8.0-dev.7/datumctl-compute_Linux_arm64.tar.gz
      sha256: e3995d4f91a09c17fcc064a1b3bdda597f7be2b94010987b1dacfa006c027b29
    - selector:
        matchLabels:
          os: darwin
          arch: amd64
      uri: https://github.com/datum-cloud/compute/releases/download/v0.8.0-dev.7/datumctl-compute_Darwin_x86_64.tar.gz
      sha256: fc74a289f804cf05a00eec070be887932d3052bfe59418a317fd5711cfcf498a
    - selector:
        matchLabels:
          os: darwin
          arch: arm64
      uri: https://github.com/datum-cloud/compute/releases/download/v0.8.0-dev.7/datumctl-compute_Darwin_arm64.tar.gz
      sha256: d33fe5a48d61d39bc2bbff78000c61c7526d1b0e81be22977cbd856d2e46e772
    - selector:
        matchLabels:
          os: windows
          arch: amd64
      uri: https://github.com/datum-cloud/compute/releases/download/v0.8.0-dev.7/datumctl-compute_Windows_x86_64.zip
      sha256: 69f79339d8151b38497ee234f9dd8fe0211f3130138beb629acc777e08dbbdeb
    - selector:
        matchLabels:
          os: windows
          arch: arm64
      uri: https://github.com/datum-cloud/compute/releases/download/v0.8.0-dev.7/datumctl-compute_Windows_arm64.zip
      sha256: d11dbd4cedcdddb6eae5671b5193922327c988f169f77df1fd76a610f0098613
- apiVersion: datumctl.datum.net/v1alpha1
  kind: Plugin
  metadata:
    name: dns
  spec:
    shortDescription: Manage DNS zones and records on Datum Cloud
    homepage: https://github.com/datum-cloud/dns-operator
    version: v0.7.0-dev.2
    platforms:
    - selector:
        matchLabels:
          os: linux
          arch: amd64
      uri: https://github.com/datum-cloud/dns-operator/releases/download/v0.7.0-dev.2/datumctl-dns_Linux_x86_64.tar.gz
      sha256: 5976ac38590d451e88e5b85dea6e760ab1f1e25ffd92f20dae9c15c250262db1
    - selector:
        matchLabels:
          os: linux
          arch: arm64
      uri: https://github.com/datum-cloud/dns-operator/releases/download/v0.7.0-dev.2/datumctl-dns_Linux_arm64.tar.gz
      sha256: 1745d0362c0f0dd8c6ba9f37786687f5a313d00d959c42a805c22f81b12c4401
    - selector:
        matchLabels:
          os: darwin
          arch: amd64
      uri: https://github.com/datum-cloud/dns-operator/releases/download/v0.7.0-dev.2/datumctl-dns_Darwin_x86_64.tar.gz
      sha256: 73c434802d6779abbc198f494d9d9106c58e197090ee71ec52ad38fcf54999ed
    - selector:
        matchLabels:
          os: darwin
          arch: arm64
      uri: https://github.com/datum-cloud/dns-operator/releases/download/v0.7.0-dev.2/datumctl-dns_Darwin_arm64.tar.gz
      sha256: 9655a0e2756223b82283347f89861cd7587df8e535ebc61a3d0083c12c4e9f62
    - selector:
        matchLabels:
          os: windows
          arch: amd64
      uri: https://github.com/datum-cloud/dns-operator/releases/download/v0.7.0-dev.2/datumctl-dns_Windows_x86_64.zip
      sha256: 96eddb1ab07d803dd5a7dc02fa0791c087829ac3116815d90182e036ff992793
